<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blog' => 'Блог',
    'Blog record successful created' => 'Запись блога успешно создана',
    'Blog record successful deleted' => 'Запись блога успешно удалена',
    'Blog record successful updated' => 'Запись блога успешно обновлена',
    'Blog records' => 'Записи блога',
    'Body' => 'Текст записи',
    'Create' => 'Добавить',
    'Create and stay here' => 'Добавить и остаться здесь',
    'Create blog record' => 'Добавить запись блога',
    'Created at' => 'Дата создания',
    'Creator' => 'Создатель',
    'Description' => 'Краткое описание',
    'Image' => 'Картинка',
    'Name' => 'Название',
    'Update' => 'Обновить',
    'Update and stay here' => 'Обновить и остаться здесь',
    'Update blog record: {name}' => 'Редактирование записи блога: {name}',
    'Updated at' => 'Дата обновления',
    'Updater' => 'Обновивший',
];
