<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blog' => '',
    'Blog record successful created' => '',
    'Blog record successful deleted' => '',
    'Blog record successful updated' => '',
    'Blog records' => '',
    'Body' => '',
    'Create' => '',
    'Create and stay here' => '',
    'Create blog record' => '',
    'Created at' => '',
    'Creator' => '',
    'Description' => '',
    'Image' => '',
    'Name' => '',
    'Update' => '',
    'Update and stay here' => '',
    'Update blog record: {name}' => '',
    'Updated at' => '',
    'Updater' => '',
];
